# Utiliser l'image officielle Node.js comme base
FROM node:18-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et le fichier package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances npm
RUN npm install

# Copier le code source dans le conteneur
COPY . .

# Construire l'application Angular en mode production
RUN npm run build --prod

# Exposer le port 80 pour le serveur web
EXPOSE 80

# Copier le fichier de configuration nginx dans le conteneur
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Définir la commande par défaut pour le conteneur
CMD ["nginx", "-g", "daemon off;"]