#Stage 1: Build the React Native web app
FROM node:14 AS build

#Define the working directory
WORKDIR /app

Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install

Copy the rest of the application source code and build the project
COPY . .
RUN npm run build

#Stage 2: Serve the built app with Nginx
FROM nginx:alpine

Copy the built app from the previous stage
COPY --from=build /app/web-build /usr/share/nginx/html

Expose the port
EXPOSE 8080

#Start Nginx server
CMD ["nginx", "-g", "daemon off;"]