name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: pokedevops

      - name: Authenticate to Google Cloud and Docker
        run: |
          echo "${{ secrets.GOOGLE_SECRET }}" > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t europe-west9-docker.pkg.dev/pokedevops/student-alban/pokemon .
          docker push europe-west9-docker.pkg.dev/pokedevops/student-alban/pokemon

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy --image=europe-west9-docker.pkg.dev/pokedevops/student-alban/pokemon --platform=managed --region=europe-west9 --allow-unauthenticated --service=service-student-alban-dev
